"""add_danh_muc_dien_thoai_table

Revision ID: 037dbe65bf8b
Revises: 6b58a9246c38
Create Date: 2026-05-02 17:37:05.557856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037dbe65bf8b'
down_revision: Union[str, Sequence[str], None] = '6b58a9246c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danh_muc_dien_thoai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_thiet_bi', sa.String(length=100), nullable=False),
    sa.Column('loai_thiet_bi', sa.String(length=100), nullable=False),
    sa.Column('thong_so_ky_thuat', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_danh_muc_dien_thoai_id'), 'danh_muc_dien_thoai', ['id'], unique=False)
    op.add_column('users', sa.Column('phone', sa.String(length=12), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'phone')
    op.drop_index(op.f('ix_danh_muc_dien_thoai_id'), table_name='danh_muc_dien_thoai')
    op.drop_table('danh_muc_dien_thoai')
    # ### end Alembic commands ###
