"""add danh_muc_camera table

Revision ID: 53ce4eb8820c
Revises: 037dbe65bf8b
Create Date: 2026-05-03 10:33:38.412484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ce4eb8820c'
down_revision: Union[str, Sequence[str], None] = '037dbe65bf8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danh_muc_camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_thiet_bi', sa.String(length=255), nullable=False),
    sa.Column('thong_so_ky_thuat', sa.String(length=255), nullable=False),
    sa.Column('hang_san_xuat', sa.String(length=255), nullable=False),
    sa.Column('nuoc_san_xuat', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_danh_muc_camera_id'), 'danh_muc_camera', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_danh_muc_camera_id'), table_name='danh_muc_camera')
    op.drop_table('danh_muc_camera')
    # ### end Alembic commands ###
