"""add vi_tri_lap_dat table

Revision ID: 81a1225741dc
Revises: 53ce4eb8820c
Create Date: 2026-05-03 20:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a1225741dc'
down_revision: Union[str, Sequence[str], None] = '53ce4eb8820c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vi_tri_lap_dat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_vi_tri', sa.String(length=255), nullable=False),
    sa.Column('mo_ta', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vi_tri_lap_dat_id'), 'vi_tri_lap_dat', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vi_tri_lap_dat_id'), table_name='vi_tri_lap_dat')
    op.drop_table('vi_tri_lap_dat')
    # ### end Alembic commands ###
